before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: pxttKzsLS49tJNtvsqwNB/XfPzgoysvn6i6Bgm5nHH5i1mgopYh1/1o41TVBQuE1ug1jdWA51V6h757DTb9KbEqg+kJXntwXShnDfKN1Uug4B5Q/ydAdKviuxRkT95mLbfkfV+THkcvla2SxyRbcUtXVwphykIKTkJuW64KzbWiijLsMl/i9C0PHsOSGJDbv/9SnHOXcOhvS7V8/zokg5CjEqkjA6g7HBxzvpC8Mm5F/Ggy2MQ2Gs2wQupL1JQ6g+5Ea2tEfQLYSpsfHWSP3zkZpKkBguT/mnltjL42DqtG4/bfTZFpwGRUkDLkR9/rJHm+N0Twv97BHAzwoIX8nsgeuBQp3vX8CeFgDasHFKZN+4dfcPlxQ5nJe/rS0jJttUyTfA4c0JbOv2D1vJyBiH4etiK1yNmr47yKpQDZL+SyRjfbhsj9XKwLoW0KAvUHM9LemsObZBxRlHQau8HAIFc+quIcwO7YeVUlN0dJgX7aTyowgqGhBnz+2X/JBWE+uzc4xhew7AL3MPOYvQC+R/6eh0IPtDFd4YMPL+H7PqaYmKxR9lSM0hRrMjJAv1hgn7TLMcoemBD5mchnwfHRgfttWkzQLj/MJ3sBEuamdUbKrYBhLw/wBj78pDmhqvt//amWXMTPDaULK3AAS0yB4rK1/25o+lDax+IUJhMfRb0c= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
